// default settings
// now specific for SQL Server

var Defaults = {
    changingRange: 'datetime',
    encapsulation: 'dbo',
    identity: 'int',
    metadataPrefix: 'Metadata',
    metadataType: 'int',
    metadataUsage: 'true',
    changingSuffix: 'ChangedAt',
    identitySuffix: 'ID',
    positIdentity: 'int',
    positGenerator: 'true',
    positingRange: 'datetime',
    positingSuffix: 'PositedAt',
    positorRange: 'tinyint',
    positorSuffix: 'Positor',
    reliabilityRange: 'decimal(5,2)',
    reliabilitySuffix: 'Reliability',
    defaultReliability: '1', // default reliability value for (unspecified) inserts
    deleteReliability: '0', // default reliability value for deletes
    assertionSuffix: 'Assertion',
    partitioning: 'false',
    entityIntegrity: 'true',
    restatability: 'true',
    idempotency: 'false',
    assertiveness: 'true',
    naming: 'improved',
    positSuffix: 'Posit',
    annexSuffix: 'Annex',
    chronon: 'datetime2(7)',
    now: 'sysdatetime()',
    dummySuffix: 'Dummy',
    versionSuffix: 'Version',
    statementTypeSuffix: 'StatementType',
    checksumSuffix: 'Checksum',
    businessViews: 'false',
    decisiveness: 'true',
    equivalence: 'false',
    equivalentSuffix: 'EQ',
    equivalentRange: 'tinyint',
    databaseTarget: 'SQLServer',
    temporalization: 'uni', 
    deletability: 'false',
    deletablePrefix: 'Deletable',
    deletionSuffix: 'Deleted',
    privacy: 'Ignore', 
    checksum: 'false',
    encryptionGroup: '',
    triggers: 'true', 
    knotAliases: 'false'
};

