/*~
-- ANCHORS AND ATTRIBUTES ---------------------------------------------------------------------------------------------
--
-- Anchors are used to store the identities of entities.
-- Anchors are immutable.
-- Attributes are used to store values for properties of entities.
-- Attributes are mutable, their values may change over one or more types of time.
-- Attributes have four flavors: static, historized, knotted static, and knotted historized.
-- Anchors may have zero or more adjoined attributes.
--
~*/
var anchor;
while (anchor = schema.nextAnchor()) {
    if(anchor.isGenerator())
        anchor.identityGenerator = 'GENERATED BY DEFAULT ON NULL AS IDENTITY';
/*~
-- Anchor table -------------------------------------------------------------------------------------------------------
-- $anchor.name table (with ${(anchor.attributes ? anchor.attributes.length : 0)}$ attributes)
-----------------------------------------------------------------------------------------------------------------------
BEGIN
    EXECUTE IMMEDIATE '
        CREATE TABLE ${anchor.capsule}$.$anchor.name (
            $anchor.identityColumnName $(anchor.isGenerator())? $anchor.identity $anchor.identityGenerator not null, : $anchor.identity not null,
            $(schema.METADATA)? $anchor.metadataColumnName $schema.metadata.metadataType not null, : $anchor.dummyColumnName number(1) null,
            constraint ${('PK_' + anchor.name).substr(0,30)}$ primary key (
                $anchor.identityColumnName
            )
        )';
EXCEPTION WHEN OTHERS THEN
    IF SQLCODE = -955 THEN NULL; ELSE RAISE; END IF;
END;
/
~*/
    var knot, attribute;
    while (attribute = anchor.nextAttribute()) {
        if(attribute.isHistorized() && !attribute.isKnotted()) {
/*~
-- Historized attribute table -----------------------------------------------------------------------------------------
-- $attribute.name table (on $anchor.name)
-----------------------------------------------------------------------------------------------------------------------
BEGIN
    EXECUTE IMMEDIATE '
        CREATE TABLE ${attribute.capsule}$.$attribute.name (
            $attribute.entityReferenceName $anchor.identity not null,
            $attribute.valueColumnName $attribute.dataRange not null,
            $attribute.changingColumnName $attribute.timeRange not null,
            $(schema.METADATA)? $attribute.metadataColumnName $schema.metadata.metadataType not null,
            constraint ${('FK_' + attribute.name).substr(0,30)}$ foreign key (
                $attribute.entityReferenceName
            ) references ${anchor.capsule}$.$anchor.name($anchor.identityColumnName),
            constraint ${('PK_' + attribute.name).substr(0,30)}$ primary key (
                $attribute.entityReferenceName,
                $attribute.changingColumnName
            )
        )';
EXCEPTION WHEN OTHERS THEN
    IF SQLCODE = -955 THEN NULL; ELSE RAISE; END IF;
END;
/
~*/
    }
    else if(attribute.isHistorized() && attribute.isKnotted()) {
        knot = attribute.knot;
/*~
-- Knotted historized attribute table ---------------------------------------------------------------------------------
-- $attribute.name table (on $anchor.name)
-----------------------------------------------------------------------------------------------------------------------
BEGIN
    EXECUTE IMMEDIATE '
        CREATE TABLE ${attribute.capsule}$.$attribute.name (
            $attribute.entityReferenceName $anchor.identity not null,
            $attribute.knotReferenceName $knot.identity not null,
            $attribute.changingColumnName $attribute.timeRange not null,
            $(schema.METADATA)? $attribute.metadataColumnName $schema.metadata.metadataType not null,
            constraint ${('FK1_' + attribute.name).substr(0,30)}$ foreign key (
                $attribute.entityReferenceName
            ) references ${anchor.capsule}$.$anchor.name($anchor.identityColumnName),
            constraint ${('FK2_' + attribute.name).substr(0,30)}$ foreign key (
                $attribute.knotReferenceName
            ) references ${knot.capsule}$.$knot.name($knot.identityColumnName),
            constraint ${('PK_' + attribute.name).substr(0,30)}$ primary key (
                $attribute.entityReferenceName,
                $attribute.changingColumnName
            )
        )';
EXCEPTION WHEN OTHERS THEN
    IF SQLCODE = -955 THEN NULL; ELSE RAISE; END IF;
END;
/
~*/
    }
    else if(attribute.isKnotted()) {
        knot = attribute.knot;
/*~
-- Knotted static attribute table -------------------------------------------------------------------------------------
-- $attribute.name table (on $anchor.name)
-----------------------------------------------------------------------------------------------------------------------
BEGIN
    EXECUTE IMMEDIATE '
        CREATE TABLE ${attribute.capsule}$.$attribute.name (
            $attribute.entityReferenceName $anchor.identity not null,
            $attribute.knotReferenceName $knot.identity not null,
            $(schema.METADATA)? $attribute.metadataColumnName $schema.metadata.metadataType not null,
            constraint ${('FK1_' + attribute.name).substr(0,30)}$ foreign key (
                $attribute.entityReferenceName
            ) references ${anchor.capsule}$.$anchor.name($anchor.identityColumnName),
            constraint ${('FK2_' + attribute.name).substr(0,30)}$ foreign key (
                $attribute.knotReferenceName
            ) references ${knot.capsule}$.$knot.name($knot.identityColumnName),
            constraint ${('PK_' + attribute.name).substr(0,30)}$ primary key (
                $attribute.entityReferenceName
            )
        )';
EXCEPTION WHEN OTHERS THEN
    IF SQLCODE = -955 THEN NULL; ELSE RAISE; END IF;
END;
/
~*/
    }
    else {
/*~
-- Static attribute table ---------------------------------------------------------------------------------------------
-- $attribute.name table (on $anchor.name)
-----------------------------------------------------------------------------------------------------------------------
BEGIN
    EXECUTE IMMEDIATE '
        CREATE TABLE ${attribute.capsule}$.$attribute.name (
            $attribute.entityReferenceName $anchor.identity not null,
            $attribute.valueColumnName $attribute.dataRange not null,
            $(schema.METADATA)? $attribute.metadataColumnName $schema.metadata.metadataType not null,
            constraint ${('FK_' + attribute.name).substr(0,30)}$ foreign key (
                $attribute.entityReferenceName
            ) references ${anchor.capsule}$.$anchor.name($anchor.identityColumnName),
            constraint ${('PK_' + attribute.name).substr(0,30)}$ primary key (
                $attribute.entityReferenceName
            )
        )';
EXCEPTION WHEN OTHERS THEN
    IF SQLCODE = -955 THEN NULL; ELSE RAISE; END IF;
END;
/
~*/
    }
}}
