/*~
-- KNOTS --------------------------------------------------------------------------------------------------------------
--
-- Knots are used to store finite sets of values, normally used to describe states
-- of entities (through knotted attributes) or relationships (through knotted ties).
-- Knots have their own surrogate identities and are therefore immutable.
-- Values can be added to the set over time though.
-- Knots should have values that are mutually exclusive and exhaustive.
--
 ~*/
var knot;
while (knot = schema.nextKnot()) {
    if(knot.isGenerator())
        knot.identityGenerator = 'GENERATED BY DEFAULT ON NULL AS IDENTITY';
    if(schema.METADATA)
       knot.metadataDefinition = knot.metadataColumnName + ' ' + schema.metadata.metadataType + ' not null';
/*~
-- Knot table ---------------------------------------------------------------------------------------------------------
-- $knot.name table
-----------------------------------------------------------------------------------------------------------------------
BEGIN
    EXECUTE IMMEDIATE '
        CREATE TABLE ${knot.capsule}$.$knot.name (
            $knot.identityColumnName $(knot.isGenerator())? $knot.identity $knot.identityGenerator not null, : $knot.identity not null,
            $knot.valueColumnName $knot.dataRange not null,
            $knot.metadataDefinition,
            constraint ${('PK_' + knot.name).substr(0,30)}$ primary key (
                $knot.identityColumnName
            ),
            constraint ${('UK_' + knot.name).substr(0,30)}$ unique (
                $knot.valueColumnName
            )
        )';
EXCEPTION WHEN OTHERS THEN
    IF SQLCODE = -955 THEN NULL; ELSE RAISE; END IF;
END;
/
~*/
}
