// the following builds specific the naming convention of Anchor Modeling, change if you want something else

// set some hard coded defaults if they are missing
schema.metadata.encapsulation = schema.metadata.encapsulation || 'anchor';
schema.metadata.chronon = schema.metadata.chronon || 'timestamp';
schema.metadata.identityProperty = 'generated by default as identity';
// TODO strip the names to 26 characters 
// or replace all the vowels (a,e,i,o,u,y) characters of the descriptor if they are not the first or last character to shrink the  total name. 
// We reserve 4 characters for prefixes. Oracle cannot handel names longer than 30 characters :-(
// Or we only use the mnemonics. Then we are also safe.    
// Create a shrink function for it.