<#
    Builds the Anchor generator that runs inside Snowflake: one SQL script that creates

      SISULATE(template, bindings)           the Sisula engine (modules/sisula.js) as a JavaScript function
      ANCHOR_BINDINGS(model_xml, temporal.)  an Anchor model, as XML, resolved to the JSON that the templates render:
                                             the same thing that Generate > JSON bindings gives in the modeler
      ANCHOR_TEMPLATE                        a table with the templates of uni, bi and crt, in render order
      ANCHOR_GENERATE(model_xml, temporal.)  the whole SQL script for a model, as one string

    It is assembled from the Anchor checkout, nothing is written by hand: the engine, the XML reader and the DOM
    facade (modules/), the map and the resolver, the scripts that prepare the schema (Helpers.js, the naming
    conventions, derive.js, exactly as the directive lists them) and the templates. The scripts that prepare the
    schema are compiled into the function, so nothing is evaluated at run time.

    Usage:
      build-snowflake-generator.ps1 [-Output <file.sql>] [-Parts <directory>] [-Anchor <checkout>]

    -Output  where to write the SQL script (default: anchor_generator.sql in the current directory)
    -Parts   also write what the SQL contains as separate files (bindings.js, sisulate.js, templates.json), which is
             what tools/hosted-check.ps1 in the sisula repository runs to compare with the golden files
#>
[CmdletBinding()]
param(
    [string] $Output = 'anchor_generator.sql',
    [string] $Parts,
    [string] $Anchor
)
Set-StrictMode -Version 2.0
$ErrorActionPreference = 'Stop'
if (-not $Anchor) { $Anchor = Split-Path -Parent $PSScriptRoot }
$Anchor = (Resolve-Path $Anchor).Path
$utf8 = New-Object Text.UTF8Encoding($false)

function Read-Source([string] $relative) {
    $path = Join-Path $Anchor $relative
    if (-not (Test-Path $path)) { throw "Not found in the Anchor checkout: $relative" }
    ([IO.File]::ReadAllText($path, [Text.Encoding]::UTF8).TrimStart([char]0xFEFF)) -replace "`r`n", "`n"
}

# The text of a function that is written as `name: function(...) { ... }` in an object, up to its closing brace.
function Get-MethodText([string] $source, [string] $header) {
    $at = $source.IndexOf($header)
    if ($at -lt 0) { throw "Cannot find '$header'" }
    $open = $source.IndexOf('{', $at)
    $depth = 0
    for ($i = $open; $i -lt $source.Length; $i++) {
        if ($source[$i] -eq '{') { $depth++ } elseif ($source[$i] -eq '}') { $depth--; if ($depth -eq 0) { return $source.Substring($at, $i - $at + 1) } }
    }
    throw "'$header' is not closed"
}

function Read-Directive([string] $temporalization) {
    $entries = (Read-Source "Snowflake_$temporalization.directive") -split "`n" | ForEach-Object { $_.Trim() } | Where-Object { $_ -and -not $_.StartsWith('#') }
    [pscustomobject]@{
        Prelude = @($entries | Where-Object { $_ -match '(^|/)(Helpers|NamingConvention|derive)\.js$' })
        Templates = @($entries | Where-Object { $_ -like '*.sisula' })
    }
}

# --- what each temporalization needs ------------------------------------------------------------------------------
$directives = [ordered]@{}
foreach ($t in 'uni', 'bi', 'crt') { $directives[$t] = Read-Directive $t }
$prelude = $directives['uni'].Prelude
foreach ($t in 'bi', 'crt') {
    if (($directives[$t].Prelude -join '|') -cne ($prelude -join '|')) { throw "Snowflake_$t.directive prepares the schema differently from Snowflake_uni.directive; the generator would have to know both." }
}

# --- the JavaScript that reads a model --------------------------------------------------------------------------
$sections = New-Object System.Collections.Generic.List[string]
$sections.Add("// The Anchor generator for Snowflake. Generated by tools/build-snowflake-generator.ps1 from the Anchor repository; do not edit.")
$sections.Add("// ---- modules/XmlTree.js`n" + (Read-Source 'modules/XmlTree.js').TrimEnd())
$sections.Add("// ---- modules/DomFacade.js`n" + (Read-Source 'modules/DomFacade.js').TrimEnd())
$sections.Add("// ---- modules/Map.js`n" + (Read-Source 'modules/Map.js').TrimEnd())
$sections.Add("// ---- Sisulator.objectify, from modules/Sisulator.js`nvar Sisulator = {`n    " + (Get-MethodText (Read-Source 'modules/Sisulator.js') 'objectify: function(xml, map)') + "`n};")
$sections.Add("// ---- modules/Resolver.js`n" + (Read-Source 'modules/Resolver.js').TrimEnd())
# The scripts that prepare the schema run in one scope, in the order of the directive, as in the modeler.
$body = New-Object System.Collections.Generic.List[string]
foreach ($p in $prelude) { $body.Add("// ---- $p`n" + (Read-Source $p).TrimEnd()) }
$sections.Add("// ---- the scripts that prepare the schema, as the directives list them`nfunction prepareSchema(schema, DEBUG, alert, console) {`n" + ($body -join "`n") + "`n}")
$sections.Add(@'
// ---- the function
var tree = XmlTree.parse(MODEL_XML);
var metadata = null;
for (var i = 0; i < tree.c.length; i++) if (tree.c[i].t === 1 && tree.c[i].n === 'metadata') metadata = tree.c[i];
if (!metadata) throw new Error('The model has no <metadata> element; it has to be an Anchor model as the modeler saves it (Generate > XML code).');
function setMetadata(name, value) {
    for (var k = 0; k < metadata.a.length; k++) if (metadata.a[k][0] === name) { metadata.a[k][1] = value; return; }
    metadata.a.push([name, value]);
}
setMetadata('databaseTarget', 'Snowflake');
if (TEMPORALIZATION !== null && TEMPORALIZATION !== undefined && TEMPORALIZATION !== '') {
    if (TEMPORALIZATION !== 'uni' && TEMPORALIZATION !== 'bi' && TEMPORALIZATION !== 'crt') throw new Error("The temporalization has to be 'uni', 'bi' or 'crt', not '" + TEMPORALIZATION + "'.");
    setMetadata('temporalization', TEMPORALIZATION);
}
var temporalization = 'uni';
for (var m = 0; m < metadata.a.length; m++) if (metadata.a[m][0] === 'temporalization') temporalization = metadata.a[m][1];
var schema = Sisulator.objectify(buildDom(tree), MAP)[MAP.root];
prepareSchema(schema, false, function () {}, { log: function () {}, error: function () {} });
return { bindingsVersion: 1, database: 'Snowflake', temporalization: temporalization, schema: Resolver.serialize(schema) };
'@)
$bindings = ($sections -join "`n`n") + "`n"
if ($bindings.Contains('$$')) { throw 'The model reader contains a doubled dollar, which would end the SQL quote of the function.' }

# --- the engine ------------------------------------------------------------------------------------------------
$engine = ((Read-Source 'modules/sisula.js') -split "`n" | Where-Object { $_ -notmatch '^\s*module\.exports\s*=\s*sisulate;\s*$' }) -join "`n"
if ($engine.Contains('$$')) { throw 'modules/sisula.js contains a doubled dollar, which would end the SQL quote of the function.' }
$sisulate = $engine.TrimEnd() + "`nreturn sisulate(TEMPLATE, BINDINGS);`n"

# --- the templates --------------------------------------------------------------------------------------------
$templates = New-Object System.Collections.Generic.List[object]
foreach ($t in $directives.Keys) {
    $position = 0
    foreach ($entry in $directives[$t].Templates) {
        $position++
        $templates.Add([pscustomobject]@{ Temporalization = $t; Position = $position; Name = [IO.Path]::GetFileNameWithoutExtension($entry); Body = (Read-Source $entry) })
    }
}

# --- provenance ----------------------------------------------------------------------------------------------
$lock = Get-Content (Join-Path $Anchor 'modules\sisula.lock.json') -Raw | ConvertFrom-Json
$commit = 'unknown'
try { $c = (& git -C $Anchor rev-parse --short HEAD 2>$null); if ($LASTEXITCODE -eq 0 -and $c) { $commit = $c.Trim() } } catch { }
$dirty = $false
try { $s = (& git -C $Anchor status --porcelain 2>$null); if ($s) { $dirty = $true } } catch { }

# --- the SQL ----------------------------------------------------------------------------------------------------
$sql = New-Object Text.StringBuilder
function Add-Line([string] $text = '') { [void] $sql.Append($text).Append("`n") }
Add-Line '-- The Anchor generator for Snowflake'
Add-Line '--'
Add-Line "-- Generated by tools/build-snowflake-generator.ps1 from the Anchor repository (commit $commit$(if ($dirty) { ', with changes that were not committed' }))"
Add-Line "-- and the Sisula engine $($lock.commit.Substring(0, 7)) ($($lock.subject)). Do not edit; build it again."
Add-Line '--'
Add-Line '-- It creates, in the current database and schema:'
Add-Line '--   SISULATE(template, bindings)              the Sisula engine'
Add-Line '--   ANCHOR_BINDINGS(model_xml, temporalization)   an Anchor model (XML as the modeler saves it) as the JSON bindings'
Add-Line '--   ANCHOR_TEMPLATE                           the templates of uni, bi and crt, in render order'
Add-Line '--   ANCHOR_GENERATE(model_xml, temporalization)   the SQL script for the model, as one string'
Add-Line '--'
Add-Line "--   SELECT ANCHOR_GENERATE('<the model XML>', 'uni');"
Add-Line '--'
Add-Line '-- The temporalization is uni, bi or crt; NULL takes the one that the model says.'
Add-Line
Add-Line '-- 1. The Sisula engine ----------------------------------------------------------------------------------'
Add-Line 'CREATE OR REPLACE FUNCTION SISULATE(TEMPLATE VARCHAR, BINDINGS VARCHAR)'
Add-Line 'RETURNS VARCHAR'
Add-Line 'LANGUAGE JAVASCRIPT'
Add-Line 'AS $$'
[void] $sql.Append($sisulate)
Add-Line '$$;'
Add-Line
Add-Line '-- 2. An Anchor model to bindings --------------------------------------------------------------------------'
Add-Line 'CREATE OR REPLACE FUNCTION ANCHOR_BINDINGS(MODEL_XML VARCHAR, TEMPORALIZATION VARCHAR)'
Add-Line 'RETURNS VARIANT'
Add-Line 'LANGUAGE JAVASCRIPT'
Add-Line 'AS $$'
[void] $sql.Append($bindings)
Add-Line '$$;'
Add-Line
Add-Line '-- 3. The templates -----------------------------------------------------------------------------------------'
Add-Line 'CREATE OR REPLACE TABLE ANCHOR_TEMPLATE ('
Add-Line '    TEMPORALIZATION VARCHAR NOT NULL,'
Add-Line '    POSITION NUMBER NOT NULL,'
Add-Line '    NAME VARCHAR NOT NULL,'
Add-Line '    BODY VARCHAR NOT NULL'
Add-Line ');'
foreach ($t in $directives.Keys) {
    Add-Line "INSERT INTO ANCHOR_TEMPLATE (TEMPORALIZATION, POSITION, NAME, BODY)"
    $rows = @($templates | Where-Object { $_.Temporalization -eq $t } | ForEach-Object {
        "SELECT '$($_.Temporalization)', $($_.Position), '$($_.Name)', BASE64_DECODE_STRING('$([Convert]::ToBase64String($utf8.GetBytes($_.Body)))')"
    })
    Add-Line ($rows -join "`nUNION ALL`n")
    Add-Line ';'
}
Add-Line
Add-Line '-- 4. The whole script for a model --------------------------------------------------------------------------'
Add-Line 'CREATE OR REPLACE FUNCTION ANCHOR_GENERATE(MODEL_XML VARCHAR, WANTED VARCHAR)'
Add-Line 'RETURNS VARCHAR'
Add-Line 'AS'
Add-Line '$$'
Add-Line 'SELECT'
Add-Line '    LISTAGG(SISULATE(t.BODY, TO_JSON(r.bindings)), '''') WITHIN GROUP (ORDER BY t.POSITION)'
Add-Line 'FROM'
Add-Line '    ANCHOR_TEMPLATE t'
Add-Line 'CROSS JOIN ('
Add-Line '    SELECT ANCHOR_BINDINGS(MODEL_XML, WANTED) AS bindings'
Add-Line ') r'
Add-Line 'WHERE'
Add-Line '    t.TEMPORALIZATION = r.bindings:temporalization::VARCHAR'
Add-Line '$$;'
$text = $sql.ToString()
# .NET resolves a relative path against the process directory, not PowerShell's, so make them absolute.
$Output = $ExecutionContext.SessionState.Path.GetUnresolvedProviderPathFromPSPath($Output)
New-Item -ItemType Directory -Force (Split-Path -Parent $Output) | Out-Null
[IO.File]::WriteAllText($Output, $text, $utf8)
Write-Host ("wrote {0}: {1:N0} characters, {2} templates, {3} scripts that prepare the schema" -f $Output, $text.Length, $templates.Count, $prelude.Count)

if ($Parts) {
    $Parts = $ExecutionContext.SessionState.Path.GetUnresolvedProviderPathFromPSPath($Parts)
    New-Item -ItemType Directory -Force $Parts | Out-Null
    [IO.File]::WriteAllText((Join-Path $Parts 'bindings.js'), $bindings, $utf8)
    [IO.File]::WriteAllText((Join-Path $Parts 'sisulate.js'), $sisulate, $utf8)
    $json = ConvertTo-Json -InputObject @($templates | ForEach-Object { @{ temporalization = $_.Temporalization; position = $_.Position; name = $_.Name; body = $_.Body } }) -Depth 4
    [IO.File]::WriteAllText((Join-Path $Parts 'templates.json'), $json, $utf8)
}
